### PR TITLE
Deleting digest from the config

### PR DESCRIPTION
**Pull request by aerograf**
Has removed, tk. there is no need for this configuration configuration. It does not affect the actions of the module and the digest function

### CODE REVIEW

**Comment by mambax7** [comment]
But doesn't it affect how you send the notifications?

**Comment by aerograf** [comment]
Does not affect. Checked. We ourselves generate and send.

**Comment by geekwright** [comment]
There is still a digest.php script that can be used for automatic generation, and it depends on this config. That could still be a preferred option in some cases.

Removing the possibility of automating the digest would be a bad idea. Although the script is a bit rough right now, automation is a must have feature for serious use.

**Comment by aerograf** [comment]
Then such an option

**Comment by geekwright** [comment]
See `\NewbbDigestHandler::checkStatus()`. It handles weekly and daily calls.

You would add a line like this to the crontab for your web host (assuming linux or similar host)

`0 6 * * * wget --post-data 'foo=bar' https://example.com/modules/newbb/digest.php`

This will run the script once per day at 0600. Then, the preference **email_digest** controls if the digest is built and mailed once each week, each day or not at all.

We do need to document it and clean the script up a little bit for security. But the option needs to stay as it was originally.

**Comment by aerograf** [comment]
I agree. It is necessary to write a detailed instruction for the user.

**Pull request closed without merging**
