### PR TITLE
Commented digest ...

### PR DESCRIPTION
**Pull request by aerograf**

### CODE REVIEW

**Comment by mambax7** [comment]
What is the purpose?

**Comment by aerograf** [comment]
This function does not work. I think it should be deleted, because there are notifications that perform the same role ...

**Comment by mambax7** [comment]
I let Richard to decide on this, since he spent more time on this.

**Comment by aerograf** [comment]
Yes. The last word for Richard. I also went through all the possible options, but I did not find an intelligible scheme. This is my proposal, but to accept it or not, it's up to you.

**Comment by geekwright** [comment]
I think #22 makes the digests fully functional. We can revisit this if needed, but will close for now.

**Pull request closed without merging**
